// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
// import { useState } from "react";
import {Orbitron, Questrial,Unbounded } from 'next/font/google'
import { GoogleAnalytics } from '@next/third-parties/google'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: 'The Verse',
  description: 'Immersive digital experiences for healing and growth',
  icons: {
    icon: '/favicon.ico'
  }

}
const orbitron = Orbitron({ subsets: ['latin'], variable: '--font-orbitron', weight: ['500', '700'] });
const questrial = Questrial({ subsets: ['latin'], variable: '--font-questrial', weight: '400' });
const unbounded = Unbounded({ subsets: ['latin'], variable: '--font-unbounded', weight: ['600', '700'] });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [navOpen, setNavOpen] = useState(false)
  return (
    <>
    <ToastContainer position="top-center"/>
<html lang="en" className={`${orbitron.variable} ${questrial.variable} ${unbounded.variable}`}>
      <body
 className="font-questrial antialiased">
      
        <Navbar />
        {children}
        <Footer />
      </body>
      {process.env.NEXT_PUBLIC_GA_ID && (
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID}/>
      )}
    </html>
      </>
  );
}
