export const People = [
     {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder and Executive Director',
    img: '/images/team-members/team-member-1.png',
    loc: 'California, USA',
    about : 'Ben creates games and experiences that uplift and connect people. As part of Catalyst 2030 and IDG Berkeley Uplift Lab, he focuses on collaboration and meaningful change.',
    special: true,
  },
   {
    name: 'Anshul Pendse',
    role: 'Co-Founder, Creative and Technical Director',
    img: '/images/team-members/team-member-2.jpeg',
    loc: 'California, USA',
    about : 'Anshul is a media artist and game designer blending entertainment, wellness, and spirituality. He holds an MFA from USC and is a PhD candidate at UC Santa Barbara.',
    special: true,
  },
   {
    name: 'Sam Wright-Edwards',
    role: 'Director, Operations',
    img: '/images/team-members/team-member-3.png',
    loc: 'Ontario, Canada',
    special: false,
  },
   {
    name: 'Alistair Song-White',
    role: 'Video Game Designer, UI/UX Designer',
    img: '/images/team-members/team-member-4.png',
    loc: 'California, USA',
    special: false,
  },
   {
    name: 'Vaishali Ramesh',
    role: 'Science and Well-Being Researcher',
    img: '/images/team-members/team-member-5.png',
    loc: 'India',
    special: false,
  },
   {
    name: 'Quenton Porter',
    role: 'Product Manager',
    img: '/images/team-members/team-member-6.png',
    loc: 'West Virginia, USA',
    special: false,
  },
   {
    name: 'Jay Jayachandran',
    role: 'Product Designer, Product Manager',
    img: '/images/team-members/team-member-7.png',
    loc: 'Nevada, USA',
    special: false,
  },
   {
    name: 'Gargi Pawar',
    role: 'Compensation Analyst',
    img: '/images/team-members/team-member-8.png',
    loc: 'Florida, USA',
    special: false,
  },
   {
    name: 'Lily Le',
    role: 'Web Developer',
    img: '/images/team-members/team-member-9.jpeg',
    loc: 'Ontario, Canada',
    special: false,
  },
   {
    name: 'Philip Sadler',
    role: 'Fellow, Yoga and Breathwork Teacher',
    img: '/images/team-members/team-member-10.jpeg',
    loc: 'California, USA',
    special: false,
  },
   {
    name: 'Sonni Daly',
    role: 'Wellness Designer and Researcher',
    img: '/images/team-members/team-member-11.png',
    loc: 'California, USA',
    special: false,
  },
   {
    name: 'James Covial',
    role: 'Unreal Designer, Sound Design, Music Producer',
    img: '/images/team-members/team-member-12.png',
    loc: 'North Carolina, USA',
    special: false,
  },
   {
    name: 'Lily Mae Pido',
    role: 'UI/UX Designer, Content Designer',
    img: '/images/team-members/team-member-13.png',
    loc: 'California, USA',
    special: false,
  },
   {
    name: 'Vidip Singh',
    role: 'Web Developer',
    img: '/images/team-members/team-member-14.png',
    loc: 'New Delhi, India',
    special: false,
  },
   {
    name: 'Xiao Liu',
    role: 'USC Doctor of Psychology PhD , Mixed Methods Researcher',
    img: '/images/team-members/team-member-15.jpeg',
    loc: 'California, USA',
    special: false,
  },
]