export const People = [
     {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-1.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-2.jpeg',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-3.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-4.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-5.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-6.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-7.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-8.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-9.jpeg',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-10.jpeg',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-11.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-12.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-13.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-14.png',
    quote: 'Designing worlds that heal.',
    special: true,
  },
   {
    name: 'Ben Simon-Thomas',
    role: 'Co-Founder & CEO',
    img: '/images/team-members/team-member-15.jpeg',
    quote: 'Designing worlds that heal.',
    special: true,
  },
]