name: Deploy to DreamHost VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DH_HOST }}
          username: ${{ secrets.DH_USER }}
          key: ${{ secrets.DH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            set -euo pipefail

            echo "== CD to project =="
            cd /home/koorosh/versebuilding.com/theverse

            echo "== Load NVM =="
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

            echo "== Use Node 18 =="
            nvm use 18

            echo "== Ensure PM2 installed =="
            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2
            fi

            echo "== Pull latest code =="
            git fetch origin
            git reset --hard origin/main

            echo "== Clean and install deps =="
            rm -rf .next
            npm ci || npm install

            echo "== Build project =="
            npm run build -- --no-lint

            echo "== Restart app with PM2 =="
            export HOST=0.0.0.0
            export PORT=8001
            if pm2 describe verse >/dev/null 2>&1; then
              pm2 restart verse --update-env
            else
              pm2 start npm --name "verse" -- start
            fi

            pm2 save
            echo "== Deployment complete =="
