name: Deploy to DreamHost VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DH_HOST }}
          username: ${{ secrets.DH_USER }}
          key: ${{ secrets.DH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/versebuilding.com/theverse
            git pull origin main
            npm install
            npm run build
            pm2 restart verse
